### ISSUE TITLE
Add radmon (radiance monitoring) codes

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-GSL/rrfs_utl#43]
## Description
We're looking to add radiance monitoring to the RRFS system.  It includes some source code that would seem to fit within this repository

## Solution
We will create a PR to add these codes, likely collecting under a single radmon/ directory.

## Alternatives (optional)
If applicable, add a description of any alternative solutions or features you've
considered.

## Related to (optional)
Directly reference any issues or PRs in this or other repositories that this is
related to, and describe how they are related.

**Comment by xyzemc** [comment]
The RadMon (radiance monitoring) package can be used to extract data from
radiance diagnostic files and visualize the results by plotting the data using
javascript or optionally GrADS.  The package also may optionally perform data
validation and error checking. It has been used in GDAS and NAM DA operational. Leveraging this package to RRFS will benefit to  monitor the radiance DA status in real time.
This issue is for adding the Data Extract step into RRFS workflow to generate the binary and .ctl file for plotting from each gsi cycle.
